version: '3.8'

services:
  atlas-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: atlas-document-management
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - SESSION_SECRET=atlas-production-secret-change-this
      - DATABASE_URL=postgresql://neondb_owner:npg_pYMIncxqy48X@ep-square-lake-adttuv8z-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    volumes:
      - ./attached_assets:/app/attached_assets:ro
      - ./logs:/app/logs
      - atlas-data:/app/data
    networks:
      - atlas-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  nginx:
    image: nginx:alpine
    container_name: atlas-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - atlas-app
    networks:
      - atlas-network

volumes:
  atlas-data:

networks:
  atlas-network:
    driver: bridge