version: '3.8'

services:
  atlas-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: atlas-document-management
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - SESSION_SECRET=atlas-production-secret-change-this
    volumes:
      - ./attached_assets:/app/attached_assets:ro
      - ./logs:/app/logs
      - atlas-data:/app/data
    networks:
      - atlas-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    
  # Optional: Add PostgreSQL database
  atlas-db:
    image: postgres:13-alpine
    container_name: atlas-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=atlas_db
      - POSTGRES_USER=atlas_user
      - POSTGRES_PASSWORD=secure_password_change_this
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - atlas-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  # Optional: Add Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: atlas-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - atlas-app
    networks:
      - atlas-network

volumes:
  atlas-data:
  postgres-data:

networks:
  atlas-network:
    driver: bridge