services:
  - type: web
    name: atlas-document-app
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: atlas-database
          property: connectionString

databases:
  - name: atlas-database
    databaseName: atlas_db
    user: atlas_user